### ISSUE TITLE
Dirt/leaves generating inside houses

### ISSUE THREAD

**Issue by Julynx** [jtorleonstudios/HUB-Better-Villages#32] opened 2023-05-20 12:01 UTC
I use Terra and Better Villages (Fabric 1.19.2) and sometimes houses are filled almost entirely with dirt or leaves blocks in the inside.

**Comment by jtorleonstudios** [comment] 2023-05-20 12:07
yes terra is not the cause of the problem, but thank you for noted it. It is a small error that should be fixed soon

**Comment by Julynx** [comment] 2023-05-20 13:46
Thanks! I took a screenshot in case it helps :)
![2023-05-20_15 45 22](https://github.com/jtorleonstudios/HUB-Better-Villages/assets/64993676/8ca225a5-bcaf-41cd-8145-c26c9c939e87)

**Comment by jtorleonstudios** [comment] 2023-05-21 14:51
yes thanks you

**Comment by jtorleonstudios** [comment] 2023-06-29 22:44
Currently (try) applicated a solution to avoid this problem, should be corrected in the next version. reopen the problem if the problem continues

**Closed by jtorleonstudios** 2023-06-29 22:44 UTC
Labels: bug
